#! /bin/sh
#
# Config file for BSPWM setup for two monitors
#
# 20repsej


#### AUTOSTART ####
xrandr --output DP-2 --primary --mode 1920x1080 --rate 144 --output HDMI-0 --mode 1920x1080 --right-of DP-2 &
setxkbmap -layout us,se -option grp:alt_shift_toggle &
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
feh --bg-fill $HOME/Pictures/wallpapers/backgroundgray.png
wal -R

### MONITORS ####
bspc monitor DP-2 -d     
bspc monitor HDMI-0 -d     

#### BSPWM configuration
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.52
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
#bspc config normal_border_color		      "#4c566a"
#bspc config active_border_color	          "#1e1e1e"
#bspc config focused_border_color	      "#5e81ac"
#bspc config presel_feedback_color	      "#5e81ac"
#bspc config urgent_border_color 	      "#dd2727"
bspc config normal_border_color '#2e303e'
bspc config active_border_color '#6c6f93'
bspc config focused_border_color '#6c6f93'

#### RULES ####
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
